spring:
  application:
    name: purchase-client
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  zipkin:
      base-url: http://localhost:8006
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
      # 设置正常关闭超时时间，如正常关闭应用程序时，给lettuce连接处池100ms关闭时间，超过则强行关闭
      shutdown-timeout: 100ms
    # 连接超时时间（毫秒）
    timeout: 10000ms
server:
  port: 10001

#开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    default:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100 # 调用线程允许请求HystrixCommand.GetFallback()的最大数量，默认10。超出时将会有异常抛出
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为100
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100 # 最大请求并发数
  threadpool:
    default:
      maximumSize: 20

purchase-service: #这是ribbon要请求的serviceID
  ribbon:
    #连接超时时间
    ConnectTimeout: 100000
    #请求处理超时时间
    ReadTimeout: 200000
    #统一服务server尝试重连1次
    MaxAutoRetries: 1
    #切换server重连1次
    MaxAutoRetriesNextServer: 1
    #服务列表
    listOfServers: http://localhost:10002

ribbon:
  eager-load:
    # 启动饥饿加载
    enabled: true
    clients: purchase-service,sales-member-service
  ConnectTimeout: 10000
  ReadTimeout: 5000
