spring:
  application:
    name: purchase-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/sipin-sales?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
        hikari:
          connection-timeout: 5000
          maximum-pool-size: 25
  redis:
    cluster:
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
      # 设置正常关闭超时时间，如正常关闭应用程序时，给lettuce连接处池100ms关闭时间，超过则强行关闭
      shutdown-timeout: 100ms
    # 连接超时时间（毫秒）
    timeout: 10000ms
  flyway:
    enabled: true
    ignore-missing-migrations: true
    out-of-order: true
    validate-on-migrate: true
  zipkin:
    base-url: http://localhost:8006

mybatis-plus:
  mapper-locations: classpath:/cn/sipin/sales/cloud/purchase/service/mapper/xml/*Mapper.xml
  global-config:
      id-type: 0
      field-strategy: 2
      db-column-underline: true
      refresh-mapper: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false

server:
  port: 10002
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    default:
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100 # 调用线程允许请求HystrixCommand.GetFallback()的最大数量，默认10。超出时将会有异常抛出
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 #缺省为100
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 100 # 最大请求并发数
  threadpool:
    default:
      maximumSize: 20
# 开启hystrix熔断和替换原生httpclient客户端
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

erp:
  config:
    XErpToken: 123456
    secret: helloworld


merchandise-service: #这是ribbon要请求的serviceID
  ribbon:
    #连接超时时间
    ConnectTimeout: 10000
    #请求处理超时时间
    ReadTimeout: 20000
    #统一服务server尝试重连1次
    MaxAutoRetries: 1
    #切换server重连1次
    MaxAutoRetriesNextServer: 1
    #服务列表
    listOfServers: http://localhost:9092

sales-member-service: #这是ribbon要请求的serviceID
  ribbon:
    #连接超时时间
    ConnectTimeout: 10000
    #请求处理超时时间
    ReadTimeout: 20000
    #统一服务server尝试重连1次
    MaxAutoRetries: 1
    #切换server重连1次
    MaxAutoRetriesNextServer: 1
    #服务列表
    listOfServers: http://localhost:7013

ribbon:
  eager-load:
    # 启动饥饿加载
    enabled: true
    clients: sales-member-service,merchandise-service
  ConnectTimeout: 10000
  ReadTimeout: 5000
payment:
  compensation:
    interval: 5
    delay: 0

logging:
  level:
    cn.sipin.sales.cloud.purchase.service: DEBUG


logging:
  config: classpath:logback-spring.xml
  # 需要根据不同的环境配置不同的路径
  path: /Users/joey/Documents/logs
  contextName: purchase-order
  appDir: purchase-order